# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.10";
      "sbtVersion" = "1.2.8";
    }];
  "repos" = {
    "nix-public" = "";
  };
  "artifacts" = {
    "nix-public/com/github/luben/zstd-jni/1.4.0-1/zstd-jni-1.4.0-1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.4.0-1/zstd-jni-1.4.0-1-javadoc.jar";
      sha256 = "E5FED2B6D7E3F942AA270939B937B0208F2F808D1DB8832336A9F3F17D315FBE";
    };
    "nix-public/com/github/luben/zstd-jni/1.4.0-1/zstd-jni-1.4.0-1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.4.0-1/zstd-jni-1.4.0-1-sources.jar";
      sha256 = "BBCB52451F1DBBDA7C2BEC87644EF93F2AD9F745AE66DFD4242699FE08376CDD";
    };
    "nix-public/com/github/luben/zstd-jni/1.4.0-1/zstd-jni-1.4.0-1.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.4.0-1/zstd-jni-1.4.0-1.jar";
      sha256 = "0D45847C7A1FC59C24EE71D942CC1FAEA6A78CE7A88BF65838358BDA2A316567";
    };
    "nix-public/com/github/luben/zstd-jni/1.4.0-1/zstd-jni-1.4.0-1.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.4.0-1/zstd-jni-1.4.0-1.pom";
      sha256 = "8A805FB405A9734573BC2FF14CBE67FBAC5C40437A7017B3317C7253E5526816";
    };
    "nix-public/dev/zio/zio-kafka_2.12/0.4.1/zio-kafka_2.12-0.4.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-kafka_2.12/0.4.1/zio-kafka_2.12-0.4.1-javadoc.jar";
      sha256 = "4550CBF7893542B07A3E76D7592D74D0BF07E0D78A7AB283370545D2A312062B";
    };
    "nix-public/dev/zio/zio-kafka_2.12/0.4.1/zio-kafka_2.12-0.4.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-kafka_2.12/0.4.1/zio-kafka_2.12-0.4.1-sources.jar";
      sha256 = "728008482646B62657D0FFA73AC0A0E79FC1D5A99DA56784E11AA21A30177E9D";
    };
    "nix-public/dev/zio/zio-kafka_2.12/0.4.1/zio-kafka_2.12-0.4.1.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-kafka_2.12/0.4.1/zio-kafka_2.12-0.4.1.jar";
      sha256 = "B8A6538F7021539B40131028CC4A73B6AE87653E25F570CC1CC033EC619AF9FA";
    };
    "nix-public/dev/zio/zio-kafka_2.12/0.4.1/zio-kafka_2.12-0.4.1.pom" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-kafka_2.12/0.4.1/zio-kafka_2.12-0.4.1.pom";
      sha256 = "7E92D73F59DFC2279DD13AEC349448BF1EC179C15862506A3898D642AC9A2A0A";
    };
    "nix-public/dev/zio/zio-stacktracer_2.12/1.0.0-RC17/zio-stacktracer_2.12-1.0.0-RC17-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-stacktracer_2.12/1.0.0-RC17/zio-stacktracer_2.12-1.0.0-RC17-javadoc.jar";
      sha256 = "A53FFE1512BC1D3DB1B34AEA09DF851DB574752A76603249327FEF23901ACF06";
    };
    "nix-public/dev/zio/zio-stacktracer_2.12/1.0.0-RC17/zio-stacktracer_2.12-1.0.0-RC17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-stacktracer_2.12/1.0.0-RC17/zio-stacktracer_2.12-1.0.0-RC17-sources.jar";
      sha256 = "87BB8A7C61F8D6359AF08EB0635ECE6F27805EBBE49EE747976D2B92C7F1E153";
    };
    "nix-public/dev/zio/zio-stacktracer_2.12/1.0.0-RC17/zio-stacktracer_2.12-1.0.0-RC17.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-stacktracer_2.12/1.0.0-RC17/zio-stacktracer_2.12-1.0.0-RC17.jar";
      sha256 = "DD43181922C418D5AB896C7F1F5F1E95EE2B5C23087A88F36E1E8979418FC36B";
    };
    "nix-public/dev/zio/zio-stacktracer_2.12/1.0.0-RC17/zio-stacktracer_2.12-1.0.0-RC17.pom" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-stacktracer_2.12/1.0.0-RC17/zio-stacktracer_2.12-1.0.0-RC17.pom";
      sha256 = "94040F70585BC20AE9DEC6C0B5655E659E6CDC60FC0C0A29FD16F21446DD3FBB";
    };
    "nix-public/dev/zio/zio-streams_2.12/1.0.0-RC17/zio-streams_2.12-1.0.0-RC17-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-streams_2.12/1.0.0-RC17/zio-streams_2.12-1.0.0-RC17-javadoc.jar";
      sha256 = "6F138C28C32B69BBEA931900345E8FFEA62A011F32737EBA3BED7104A3A2622C";
    };
    "nix-public/dev/zio/zio-streams_2.12/1.0.0-RC17/zio-streams_2.12-1.0.0-RC17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-streams_2.12/1.0.0-RC17/zio-streams_2.12-1.0.0-RC17-sources.jar";
      sha256 = "E77EBD39BBECA257F0A774E5D10015CFFC0B0B2728F574640B2E6C53DA269120";
    };
    "nix-public/dev/zio/zio-streams_2.12/1.0.0-RC17/zio-streams_2.12-1.0.0-RC17.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-streams_2.12/1.0.0-RC17/zio-streams_2.12-1.0.0-RC17.jar";
      sha256 = "640CFA72EDC83708B51D454046F4E87BD2A0357141CCF68BF82AACCC736D2A65";
    };
    "nix-public/dev/zio/zio-streams_2.12/1.0.0-RC17/zio-streams_2.12-1.0.0-RC17.pom" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio-streams_2.12/1.0.0-RC17/zio-streams_2.12-1.0.0-RC17.pom";
      sha256 = "91C35EECFDA227FB4E56A14C54155783465351E61ACA7F2F5D85F34A57E2EA83";
    };
    "nix-public/dev/zio/zio_2.12/1.0.0-RC17/zio_2.12-1.0.0-RC17-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio_2.12/1.0.0-RC17/zio_2.12-1.0.0-RC17-javadoc.jar";
      sha256 = "253281502293838E80BA8E58A4E8F51777AA32E43D42AC8B51436494AAEBCC1A";
    };
    "nix-public/dev/zio/zio_2.12/1.0.0-RC17/zio_2.12-1.0.0-RC17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio_2.12/1.0.0-RC17/zio_2.12-1.0.0-RC17-sources.jar";
      sha256 = "0FB84FD9ED5DBF8B1FAF903B349842B11CAD86EA61E93B04E7E9E75F17BAC537";
    };
    "nix-public/dev/zio/zio_2.12/1.0.0-RC17/zio_2.12-1.0.0-RC17.jar" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio_2.12/1.0.0-RC17/zio_2.12-1.0.0-RC17.jar";
      sha256 = "35ADE72B393FF4DC6F43F00A7C8A3E7E6C9FE4B09135C587380D361CE87FFDFB";
    };
    "nix-public/dev/zio/zio_2.12/1.0.0-RC17/zio_2.12-1.0.0-RC17.pom" = {
      url = "https://repo1.maven.org/maven2/dev/zio/zio_2.12/1.0.0-RC17/zio_2.12-1.0.0-RC17.pom";
      sha256 = "4132B01278D3B7AA4D28927D8FCC7AB3827740FDE69D8A7C1A5EA67B6B738C3F";
    };
    "nix-public/io/argonaut/argonaut_2.12/6.2.2/argonaut_2.12-6.2.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/argonaut/argonaut_2.12/6.2.2/argonaut_2.12-6.2.2-javadoc.jar";
      sha256 = "F710D2A32AE68C120C0A2DD40FCD3AAAB35370DCE8C3FF42B90095BA14AA84D7";
    };
    "nix-public/io/argonaut/argonaut_2.12/6.2.2/argonaut_2.12-6.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/argonaut/argonaut_2.12/6.2.2/argonaut_2.12-6.2.2-sources.jar";
      sha256 = "6225FA1AEDD473F05DE943B426405C87DB6A5AC05EF2466E9C187B42A923E8C0";
    };
    "nix-public/io/argonaut/argonaut_2.12/6.2.2/argonaut_2.12-6.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/io/argonaut/argonaut_2.12/6.2.2/argonaut_2.12-6.2.2.jar";
      sha256 = "3548F7367F613E82F2093277ECA172EA9AE3CFEAEF9ABA3C094C6E9D0E3AE0F0";
    };
    "nix-public/io/argonaut/argonaut_2.12/6.2.2/argonaut_2.12-6.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/io/argonaut/argonaut_2.12/6.2.2/argonaut_2.12-6.2.2.pom";
      sha256 = "73143B55C749BF3841963E084DA727F2E0CF00121A475CD2C2A5DF81953B9E45";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-javadoc.jar";
      sha256 = "EBD162363C0A6CA9E52AF51D7377F78F559D3F2663DC896E0DBF3B16A0188972";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-sources.jar";
      sha256 = "319A840705E1E46ABE579DD3D079B508558791E0236BC78DA01911748E06AF93";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-tests.jar";
      sha256 = "AE143A7DC135371F446A44775E8D5337D97151D5FEEC8CA8575F3A718DDF35F3";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar";
      sha256 = "97D1ACAAC82409BE42E622D7A54D3AE9D08517E8AEFDEA3D2BA9791150C2F02D";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom";
      sha256 = "1DF7B6F08DFB81A268D6B93B659A6A9E389C5D8C32BDF0754238BA6483A4E982";
    };
    "nix-public/org/apache/kafka/kafka-clients/2.3.1/kafka-clients-2.3.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.3.1/kafka-clients-2.3.1-javadoc.jar";
      sha256 = "7BE12BCA650877A44835217685521B79ACE437DEEA5C9E0D81B527F7F19921A9";
    };
    "nix-public/org/apache/kafka/kafka-clients/2.3.1/kafka-clients-2.3.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.3.1/kafka-clients-2.3.1-sources.jar";
      sha256 = "1B956D9CF3D977CCA423424F87170E969CEBC48EDCED1C2E1F850696326D294D";
    };
    "nix-public/org/apache/kafka/kafka-clients/2.3.1/kafka-clients-2.3.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.3.1/kafka-clients-2.3.1.jar";
      sha256 = "1426FAEB8385F3B2174428FAE092260862BFD9B78504D3839E1F84891CAD7396";
    };
    "nix-public/org/apache/kafka/kafka-clients/2.3.1/kafka-clients-2.3.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.3.1/kafka-clients-2.3.1.pom";
      sha256 = "400BFF267093965F7924950E49432FD5333DF718C791D3B8B3DDF76D123DF525";
    };
    "nix-public/org/fusesource/fusesource-pom/1.11/fusesource-pom-1.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.11/fusesource-pom-1.11.pom";
      sha256 = "695DB8335E33DE3D403B3D1F0425970F3710A9DB4A528EC460199055EF1E8AB8";
    };
    "nix-public/org/fusesource/jansi/jansi-project/1.12/jansi-project-1.12.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi-project/1.12/jansi-project-1.12.pom";
      sha256 = "B1B3D0FDFA827AE3911227DA5DBF9DF0F62CFF2A60F722D1DB694380B184A1F2";
    };
    "nix-public/org/fusesource/jansi/jansi/1.12/jansi-1.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12-javadoc.jar";
      sha256 = "B74CB5DDD7DFD5CDCC09A4A9D640CCBD8816D3A12020DED34531D6F67D2C54C3";
    };
    "nix-public/org/fusesource/jansi/jansi/1.12/jansi-1.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12-sources.jar";
      sha256 = "708C50198274289010BCCC651938BC64DE2AA8D9CE3F128438F92D7D338F2007";
    };
    "nix-public/org/fusesource/jansi/jansi/1.12/jansi-1.12.jar" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12.jar";
      sha256 = "8430808A03CC7A1F49F90132F7517A43CD7493390077AE4390445432826D4811";
    };
    "nix-public/org/fusesource/jansi/jansi/1.12/jansi-1.12.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12.pom";
      sha256 = "AB07889615C36BA19C11963EFEF6F3601487E8218C44ACC4BF1E311C3F00FA8D";
    };
    "nix-public/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0-javadoc.jar";
      sha256 = "A03E2B105997462507F987A1318D68D58E6CFA80B839552838AE6B7098798355";
    };
    "nix-public/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0-sources.jar";
      sha256 = "DB7727C82C150CEC38A422B9692F6431150EA2C0C0D0C723BDF7FE6946149041";
    };
    "nix-public/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0.jar";
      sha256 = "D229545AA2B1D5203C876614BDBCFFCACC303697F4F8F26F764E1D6C1ED2E416";
    };
    "nix-public/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0.pom";
      sha256 = "756E5B823A7831057447D0D66771FB1B623A7F4CEB770DF5E727AE9B1FEB0CC7";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-javadoc.jar";
      sha256 = "7B7C26DC48B443E1268F8235AE009409C26AC80D976E313B4F3F7740C227AE59";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar";
      sha256 = "8FBE3FA9E748F24AA6D6868C0C2BE30D41A02D20428ED5429BB57A897CB756E3";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar";
      sha256 = "24985EB43E295A9DD77905ADA307A850CA25ACF819CDB579C093FC6987B0DBC2";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom";
      sha256 = "A5500678F39B9B8C962A8FEE98359E9E2F2A4E5D434F3501762B30188642A2F5";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar";
      sha256 = "FF42809FBF887885C957B3D368A909C6CCDDEA4C0485E4FE3A6465ED7747B636";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar";
      sha256 = "A7E8AAC79394DF396AFDA98B35537791809D815CE15AB2224F7D31E50C753922";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar";
      sha256 = "7CC3B6CEB56E879CB977E8E043F4BFE2E062F78795EFD7EFA09F85003CB3230A";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom";
      sha256 = "A8FDB9C75E3333D442F2CBE283F1E0F8573FF33F87CFE6DC22D154ABD0D29A0B";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0-javadoc.jar";
      sha256 = "46DD8A7AC39249FD9EFD5F4A9748F31462F63DC9C4AAA822A3348DFC766FDAF9";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0-sources.jar";
      sha256 = "288FDCE0B296DF28725707CC87CFF0F65EF435C54E93E0C1FBC5A7FCC8E19ADE";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0.jar";
      sha256 = "1B48DC206F527B7604EF32492ADA8E71706C63A65D999E0CABDAFDC5793B4D63";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.2.0/scala-xml_2.12-1.2.0.pom";
      sha256 = "44EC063AD46DF37A3A5E7B25ED11E116F858BC581888C371DEA8E85AD5B211DC";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10-javadoc.jar";
      sha256 = "CD19529392E0EA64768ECA0CE23F27EC9FAAEBC924BFFAF929230F2C4AEF5B3B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10-sources.jar";
      sha256 = "BB695D1B05C5239BB93EF4B07023993A59DF073BA6150F541725D81F1CC23E4D";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10.jar";
      sha256 = "CEDC3B9C39D215A9A3FFC0CC75A1D784B51E9EDC7F13051A1B4AD5AE22CFBC0C";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10.pom";
      sha256 = "6DDA358CFC7646F44B96F68ADF99605A765AD417C2ADD82EFDDF8D69AD5612E6";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-javadoc.jar";
      sha256 = "BE85F3E1CBC005C4111019D0A84D4AEC2E5438BD1BDDD8CC2EFEF847F1BBE3A9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-sources.jar";
      sha256 = "456B9B5A0CD6581923E8938305EAE7A61976706B4E771EF158FAF25F85F882DC";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar";
      sha256 = "0E72EC4EA955D0BAD7F1A494E8DF95163F1631DF0CE8EC4F9F278FE4D5FD1824";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom";
      sha256 = "093CA3B7FD4C3D48222F30DA4526808E3E8EF2D4456D1E75793F105D437A24EA";
    };
    "nix-public/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10-javadoc.jar";
      sha256 = "8782B9DEAE7CC1FD99D9091A8BBE59901B6774670B0C44D084924C680BCB4F1A";
    };
    "nix-public/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10-sources.jar";
      sha256 = "A6F873AEB9B861848E0D0B4EC368A3F1682E33BDF11A82CE26F0BFE5FB197647";
    };
    "nix-public/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.jar";
      sha256 = "0A57044D10895F8D3DD66AD4286891F607169D948845AC51E17B4C1CF0AB569D";
    };
    "nix-public/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.pom";
      sha256 = "B7340BF1930762BF5052B69B5E28BE646076A1B210260A7C407A099648617669";
    };
    "nix-public/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6-javadoc.jar";
      sha256 = "19ADE75C094BA520EE7748DFDA58A5259E16342C9E79AE1EC217D330CE7ACDF2";
    };
    "nix-public/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6-sources.jar";
      sha256 = "E1B905FD404095BCFF7E26E750C396C7B4B193044F60555147142D24427AEAF6";
    };
    "nix-public/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.jar";
      sha256 = "F81D7144F0CE1B8123335B72BA39003C4BE2870767ACA15DD0888BA3DAB65E98";
    };
    "nix-public/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.pom";
      sha256 = "B8572EF09B9778332370F6C6F3D89029D371CA3245271664162349FFBBEAA0B1";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar";
      sha256 = "9940E7CF343DFBDDDEB60B538E559496B836430400575405FE46C7176B95C78E";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar";
      sha256 = "11482BCB49B2E47BAEE89C3B1AE10C6A40B89E2FBB0DA2A423E062F444E13492";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar";
      sha256 = "321FB55685635C931EBA4BC0D7668349DA3F2C09AEE2DE93A70566066FF25C28";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom";
      sha256 = "22E81EE9D5349BA0E897ADB5C7FCEC25656C9E0B7B86C3E93E9A7AF360481C0D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10-javadoc.jar";
      sha256 = "A3D140669ABD6D20ED57FDFAF6D62029A00A3705FF0617EEFA085158C14FEA65";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10-sources.jar";
      sha256 = "C3A883670038F8030C41E5E3840D592E2C8BD89BF33D7D42A15C60F1207B9A32";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10.jar";
      sha256 = "56B609E1BAB9144FB51525BFA01CCD72028154FC40A58685A1E9ADCBE7835730";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10.pom";
      sha256 = "E8C5D5D2A7E3E2A62AB8650577A0AEBFD5B57CF3EA9601D928422DC29FBB2C73";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6-javadoc.jar";
      sha256 = "DA80EA58F513147C3F6DBC834704A6BE7CEA09B397CE9FDD5C0D0165FEDCDA84";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6-sources.jar";
      sha256 = "F30B396D82485470A6F9B1AEF955CB70426F8C0CD72B00C37CB68B363F4939DE";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.jar";
      sha256 = "FFA70D522FC9F9DEEC14358AA674E6DD75C9DFA39D4668EF15BB52F002CE99FA";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.pom";
      sha256 = "5923BC4D2DEC0A838E013CB938E3C14AC7204B4C0DB0FB83A3E1ABBA3553CBD0";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-javadoc.jar";
      sha256 = "F7D299D01D190E239144A4C74D4EB33FA92C057B1D8F161FB7D75FD07E6426C4";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-sources.jar";
      sha256 = "5C676791217D9B48560496556B8965CCEABCBFDBB65BBEBDC52E99C0A3847735";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar";
      sha256 = "4D6405395C4599CE04CEA08BA082339E3E42135DE9AAE2923C9F5367E957315A";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.pom";
      sha256 = "CBFFFF8D495FFD66C1234469A2965F54A82FA58E6816EE0E5803E896CAC167C3";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-javadoc.jar";
      sha256 = "58CAA3EAE25920DFBA5FACBC0C449CBA01994982E96C992D080E0EE52F886AE2";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-sources.jar";
      sha256 = "4589D87CC22D0C370BD1708F328D31B98B4BAED38D1BAA8F595CA1BD5CA528E6";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar";
      sha256 = "C342EAB071B314D125B3AC00C3CE3B2287A478A64639AD210BE7FFC25835CE01";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.pom";
      sha256 = "EBF9B8ED3CCEF14B5D8904401C60D92E32B276C12CD0A152C671D184EFF28C97";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-javadoc.jar";
      sha256 = "9DD282695276A298DB294BE7C50663D750598DDF1F4C07B5B54E9D48DEE5445E";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-sources.jar";
      sha256 = "5EDF42C3DE05267BD79F413EA22CDB7C53B99719395387E4A988D087DE7B2212";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar";
      sha256 = "502C7F02FF1F99E7B125537A456601AAF31A24C997BBC265C24CA6DD3B7442BD";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.pom";
      sha256 = "1DBE0A87AE1489F9419A416F96DB4D3EE12B351CB58A09B8EB9C8E8447AE5A92";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-javadoc.jar";
      sha256 = "A63861B771C20DF0DAB78F26A4FDD573C065FC569DDEF9C907A427B2F57C98A5";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar";
      sha256 = "C314491C9DF4F0BD9DD125EF1D51228D70BD466EE57848DF1CD1B96AEA18A5AD";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar";
      sha256 = "15F70B38BB95F3002FEC9AEA54030F19BB4ECFBAD64C67424B5E5FEA09CD749E";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "61BA06A9D0C226E10F048004FCEBFB300FDD9B077D05ED502E9875324C8B762E";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-javadoc.jar";
      sha256 = "D3421C2A8450FCF646ECCEADE47B5D8F3280BE3A68D8178C11DC2F8BF2EE0375";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-sources.jar";
      sha256 = "A41F082F90CFE665755AEDB007F0F82BA8499D4EF0F58253AFDD79DD3A1C63BA";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar";
      sha256 = "ADB18E5F79A028F2B33506CCC6A4B24500DD985628B05308A7AF5ACBD1EE2CD7";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.pom";
      sha256 = "7DE9EC96F383FCC18C17A0E7513071EC929F21D1CFD81EFC028BB307CC7E9BB7";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26-javadoc.jar";
      sha256 = "9D0D38F022284C2687CF678DEBB953D4D7A63F9A31A1EE6B8C46AD6163430E3C";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26-sources.jar";
      sha256 = "9E25AD98A324E6685752FD01FBBD0588CEEC5DF564E53C49486946A2D19DC482";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26-tests.jar";
      sha256 = "D46C949CF3FADE47E45D9F24DDA02B657DD1D0802EEE0F334B5211439D523765";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar";
      sha256 = "6D9E5B86CFD1DD44C676899285B5BB4FA0D371CF583E8164F9C8A0366553242B";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.pom";
      sha256 = "8392B80830ED0D6A714235EB9A06CC26E46619EF4BEC53A2233E1DC34B8DB949";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.26/slf4j-parent-1.7.26.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.26/slf4j-parent-1.7.26.pom";
      sha256 = "35D115B3C99730EC8A08B0FC2CB31CFBE633E7933C4FB63805E01A120BF4175E";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
    "nix-public/org/specs2/specs2-common_2.12/4.7.0/specs2-common_2.12-4.7.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-common_2.12/4.7.0/specs2-common_2.12-4.7.0-javadoc.jar";
      sha256 = "CA41EC8A2DA0FDB89A5EE1A0A7352D879E60C0ED8B01D74923538B216292491F";
    };
    "nix-public/org/specs2/specs2-common_2.12/4.7.0/specs2-common_2.12-4.7.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-common_2.12/4.7.0/specs2-common_2.12-4.7.0-sources.jar";
      sha256 = "49D15A046FAB2A52CBBAF74E7D11500E0B0231F71F309A581C05089E62528658";
    };
    "nix-public/org/specs2/specs2-common_2.12/4.7.0/specs2-common_2.12-4.7.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-common_2.12/4.7.0/specs2-common_2.12-4.7.0.jar";
      sha256 = "3ADF0501036081F8314853030775DDA79D879DBD9B57F4EC6836F2B220F84DFA";
    };
    "nix-public/org/specs2/specs2-common_2.12/4.7.0/specs2-common_2.12-4.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-common_2.12/4.7.0/specs2-common_2.12-4.7.0.pom";
      sha256 = "F0131ECAF1FC215237835E09DF7C2C2D6FBA6E665B8D3EDB343A3ADE13DFDA13";
    };
    "nix-public/org/specs2/specs2-core_2.12/4.7.0/specs2-core_2.12-4.7.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-core_2.12/4.7.0/specs2-core_2.12-4.7.0-javadoc.jar";
      sha256 = "949DE91C0A722D16BFD12340F07165D8F6DD15FB8E5413A1AB44D92E6F2FBEE5";
    };
    "nix-public/org/specs2/specs2-core_2.12/4.7.0/specs2-core_2.12-4.7.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-core_2.12/4.7.0/specs2-core_2.12-4.7.0-sources.jar";
      sha256 = "3CE357D6143A2C8457059A86206552001D3BBDADAB5199E71389FD9270190079";
    };
    "nix-public/org/specs2/specs2-core_2.12/4.7.0/specs2-core_2.12-4.7.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-core_2.12/4.7.0/specs2-core_2.12-4.7.0.jar";
      sha256 = "F34C0BDDAB74432CB0524F18DDAE92369936CFD40F76F896857C2F193357018D";
    };
    "nix-public/org/specs2/specs2-core_2.12/4.7.0/specs2-core_2.12-4.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-core_2.12/4.7.0/specs2-core_2.12-4.7.0.pom";
      sha256 = "ECB9AC47F41E9896749D2E4DE0FAAE4DADF93CDC14EEA1E9A5C77A9EFEB4E414";
    };
    "nix-public/org/specs2/specs2-fp_2.12/4.7.0/specs2-fp_2.12-4.7.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-fp_2.12/4.7.0/specs2-fp_2.12-4.7.0-javadoc.jar";
      sha256 = "75782A50FD1F9232B33479EBBEFE3BFF69D48A2DFC3C8C68981D20085F11FF12";
    };
    "nix-public/org/specs2/specs2-fp_2.12/4.7.0/specs2-fp_2.12-4.7.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-fp_2.12/4.7.0/specs2-fp_2.12-4.7.0-sources.jar";
      sha256 = "FB7C9E16589A19BED1002A5AB9D473151EC8B2BD6253E13877FE53749B349DD8";
    };
    "nix-public/org/specs2/specs2-fp_2.12/4.7.0/specs2-fp_2.12-4.7.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-fp_2.12/4.7.0/specs2-fp_2.12-4.7.0.jar";
      sha256 = "279BAAC59790C83F7DE0DE03AD7FC468F4DD5594F94DC2BC12E35D8D7694C4A1";
    };
    "nix-public/org/specs2/specs2-fp_2.12/4.7.0/specs2-fp_2.12-4.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-fp_2.12/4.7.0/specs2-fp_2.12-4.7.0.pom";
      sha256 = "C178D6B9B97B67428583BAC460EE946D6A4FA4A9E96BD77CD33303B9DDC65F35";
    };
    "nix-public/org/specs2/specs2-matcher_2.12/4.7.0/specs2-matcher_2.12-4.7.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-matcher_2.12/4.7.0/specs2-matcher_2.12-4.7.0-javadoc.jar";
      sha256 = "17DA5132C484AC627934FD94CE9B24D158981A8D54C29E473560394CD2CC1FC0";
    };
    "nix-public/org/specs2/specs2-matcher_2.12/4.7.0/specs2-matcher_2.12-4.7.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-matcher_2.12/4.7.0/specs2-matcher_2.12-4.7.0-sources.jar";
      sha256 = "D2EC230CEA850DB83045A549B9F5897020F953252D5CF70C04294D8828E27BA0";
    };
    "nix-public/org/specs2/specs2-matcher_2.12/4.7.0/specs2-matcher_2.12-4.7.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-matcher_2.12/4.7.0/specs2-matcher_2.12-4.7.0.jar";
      sha256 = "E15A253FED025DB193C63A188EB212C2BB7160AB6BB70A9A841BBC2686BCA18B";
    };
    "nix-public/org/specs2/specs2-matcher_2.12/4.7.0/specs2-matcher_2.12-4.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/specs2/specs2-matcher_2.12/4.7.0/specs2-matcher_2.12-4.7.0.pom";
      sha256 = "93F7C6F7FB4316A99DBD297FD16BADF5465192ACEBB9BBD0543F9EFDB5F8AD18";
    };
    "nix-public/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3-javadoc.jar";
      sha256 = "C3FD85C43BE2CEDBFD555771A94D57D4E5AF3B3FFE2385C1E86661AD742B9460";
    };
    "nix-public/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3-sources.jar";
      sha256 = "08398A9FC461F267ECB58AF61CC2B98DDB470C00CB6FB39B88C745F38CD33803";
    };
    "nix-public/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.jar";
      sha256 = "7EEA31C0A25D35CD092D8AEC08BED04F22152409B58D63D43839074A9AB7AB97";
    };
    "nix-public/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.pom";
      sha256 = "07CE1236617C8C1B74A9DE23B5A09DF9A598930DF828383DB2ACFA3BF1617505";
    };
  };
}
